name: Build CEO Ticket Issuance APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        api-level: 34
        target: google_apis
        arch: x86_64
        profile: Nexus 6
      
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: wrapper
          
    - name: Accept Android SDK licenses
      run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true
        
    - name: Validate Gradle wrapper
      run: |
        cd android-project
        if [ ! -f gradle/wrapper/gradle-wrapper.jar ]; then
          echo "Wrapper JAR missing, downloading..."
          curl -L -o gradle/wrapper/gradle-wrapper.jar https://github.com/gradle/gradle/raw/v8.4.0/gradle/wrapper/gradle-wrapper.jar
        fi
        chmod +x gradlew
        
    - name: Disable Gradle configuration cache for CI
      run: |
        cd android-project
        echo "org.gradle.configuration-cache=false" >> gradle.properties
        echo "org.gradle.caching=false" >> gradle.properties
        
    - name: Debug project structure
      run: |
        cd android-project
        echo "=== Project Structure ==="
        ls -la
        echo "=== App directory ==="
        ls -la app/
        echo "=== Build files ==="
        ls -la *.gradle* || echo "No gradle files found"
        echo "=== Gradle properties ==="
        cat gradle.properties
        
    - name: Clean and Build Debug APK
      run: |
        cd android-project
        ./gradlew clean assembleDebug --no-daemon --no-build-cache --no-configuration-cache --stacktrace --info
        
    - name: Build Release APK
      run: |
        cd android-project
        ./gradlew assembleRelease --no-daemon --no-build-cache --no-configuration-cache --stacktrace
        
    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        path: android-project/app/build/outputs/apk/debug/app-debug.apk
        
    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release-apk
        path: android-project/app/build/outputs/apk/release/app-release-unsigned.apk
        
    - name: Create Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: build-${{ github.run_number }}
        name: Build ${{ github.run_number }}
        body: |
          🚀 CEO Ticket Issuance - Phase 6 Build
          
          ## Features
          - ✅ Complete ticket issuance system
          - ✅ TMA 2004 compliance
          - ✅ Digital signature capture
          - ✅ ANPR integration
          - ✅ Timer management
          - ✅ Ticket printing
          - ✅ Ticket history
          
          ## Installation
          1. Download app-debug.apk
          2. Install on Android device (API 24+)
          3. Login with Test/Test
          4. Follow testing guide in repository
          
          ## Testing Flow
          Dashboard → New Observation → Camera → Form → Timer → Ticket → History
          
          Build: ${{ github.sha }}
          Date: ${{ github.event.head_commit.timestamp }}
        files: |
          android-project/app/build/outputs/apk/debug/app-debug.apk
          android-project/app/build/outputs/apk/release/app-release-unsigned.apk
        draft: false
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}