name: Build CEO Ticket Issuance APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Make gradlew executable
      run: |
        cd android-project
        chmod +x gradlew
        
    - name: Build Debug APK
      run: |
        cd android-project
        ./gradlew assembleDebug --no-daemon
        
    - name: Build Release APK
      run: |
        cd android-project
        ./gradlew assembleRelease --no-daemon
        
    - name: Upload Debug APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug-apk
        path: android-project/app/build/outputs/apk/debug/app-debug.apk
        
    - name: Upload Release APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release-apk
        path: android-project/app/build/outputs/apk/release/app-release-unsigned.apk
        
    - name: Create Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: build-${{ github.run_number }}
        name: Build ${{ github.run_number }}
        body: |
          🚀 CEO Ticket Issuance - Phase 6 Build
          
          ## Features
          - ✅ Complete ticket issuance system
          - ✅ TMA 2004 compliance
          - ✅ Digital signature capture
          - ✅ ANPR integration
          - ✅ Timer management
          - ✅ Ticket printing
          - ✅ Ticket history
          
          ## Installation
          1. Download app-debug.apk
          2. Install on Android device (API 24+)
          3. Login with Test/Test
          4. Follow testing guide in repository
          
          ## Testing Flow
          Dashboard → New Observation → Camera → Form → Timer → Ticket → History
          
          Build: ${{ github.sha }}
          Date: ${{ github.event.head_commit.timestamp }}
        files: |
          android-project/app/build/outputs/apk/debug/app-debug.apk
          android-project/app/build/outputs/apk/release/app-release-unsigned.apk
        draft: false
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}