name: Build CEO Ticket Issuance APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        cmdline-tools-version: 11076708
      
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        cache-disabled: true
      
    - name: Accept Android SDK licenses
      run: |
        echo "ANDROID_HOME: $ANDROID_HOME"
        echo "Available cmdline-tools versions:"
        ls -la $ANDROID_HOME/cmdline-tools/ || echo "No cmdline-tools found"
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true
        
    - name: Make gradlew executable
      run: |
        cd android-project
        chmod +x gradlew
        
    - name: Check Gradle version
      run: |
        cd android-project
        ./gradlew --version
        
    - name: List project structure
      run: |
        cd android-project
        echo "=== Project Root ==="
        ls -la
        echo "=== App directory ==="
        ls -la app/
        echo "=== App build.gradle ==="
        head -20 app/build.gradle.kts
        echo "=== Gradle properties ==="
        cat gradle.properties
        
    - name: Clean project
      run: |
        cd android-project
        ./gradlew clean --no-daemon --no-configuration-cache --stacktrace
        
    - name: Build Debug APK
      run: |
        cd android-project
        ./gradlew assembleDebug --no-daemon --no-configuration-cache --stacktrace --info
        
    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: app-debug-apk
        path: android-project/app/build/outputs/apk/debug/app-debug.apk
        
    - name: Build Release APK
      run: |
        cd android-project
        ./gradlew assembleRelease --no-daemon --no-configuration-cache --stacktrace
        
    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: app-release-apk
        path: android-project/app/build/outputs/apk/release/app-release-unsigned.apk
        
    - name: Create Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main' && success()
      uses: softprops/action-gh-release@v1
      with:
        tag_name: build-${{ github.run_number }}
        name: Build ${{ github.run_number }}
        body: |
          🚀 CEO Ticket Issuance - Phase 6 Build
          
          ## Features
          - ✅ Complete ticket issuance system
          - ✅ TMA 2004 compliance
          - ✅ Digital signature capture
          - ✅ ANPR integration
          - ✅ Timer management
          - ✅ Ticket printing
          - ✅ Ticket history
          
          ## Installation
          1. Download app-debug.apk
          2. Install on Android device (API 24+)
          3. Login with Test/Test
          4. Follow testing guide in repository
          
          ## Testing Flow
          Dashboard → New Observation → Camera → Form → Timer → Ticket → History
          
          Build: ${{ github.sha }}
          Date: ${{ github.event.head_commit.timestamp }}
        files: |
          android-project/app/build/outputs/apk/debug/app-debug.apk
          android-project/app/build/outputs/apk/release/app-release-unsigned.apk
        draft: false
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}